version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - npm install --force
      - npm run build
  post_build:
    commands:
      - npm start

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  exclude-paths:
    - 'node_modules'
    - 'build_logs'
