export default function privacypolicy(){
	return(
		  <div className="max-w-[1000px] mx-auto text-xs mt-10 bg-white px-4">
		  	
		  	<h1 className="text-3xl py-2">Terms and Conditions</h1>
DogSwag is a brand owned and managed by DogSwag India Limited (hereinafter referred to as “us”, “we”, “our” or “Company”) a company incorporated under the Companies Act, 2013. The Company aims at providing pet parents and bloggers with an opportunity to share their knowledge, stories, and support and help with other pet parents who consume it. The domain name https://dogswag.club/ (hereinafter referred to as “Website”) is also operated and maintained by the Company.
The Website is a homage to dogs and lists down experiences, stories, knowledge, help, and support. The aim of the Company is to assist parents/guardians (“you”) visiting, accessing, or using the Website to empower, enlighten, engage, buy, seek, and provide help, support, and advise for themselves and for the welfare of their dogs. 
PLEASE READ THE FOLLOWING TERMS AND CONDITIONS CAREFULLY. BY ACCESSING AND USING OUR WEBSITE YOU HAVE READ, UNDERSTOOD AND AGREE TO BE LEGALLY BOUND BY THESE TERMS AND CONDITIONS. IN CASE YOU DO NOT AGREE TO THESE TERMS AND CONDITIONS, KINDLY DO NOT ACCESS OR USE THIS WEBSITE OR SOFTWARE ANY FURTHER.
These Terms and Conditions constitute a legally binding agreement between you and the Company, who shall collectively be referred to as “Party” or “Parties”. You accept these Terms and Conditions when you use our website each time You access and use these platforms thereafter. If you do not accept or agree to these Terms and Conditions, you must discontinue using the Website and the services provided therein.
Services
The services constitute a WEBSITE for sharing of knowledge, stories, buying, selling, seeking, and providing, help, support, and advise from blogs which are shared as part of our life experiences. The blogs are written by pet parents or pet bloggers who provide this information based on their knowledge and understanding of dogs. 
Registration
In order to become a member and write a blog you would first need to get invited by a fellow member or get invited by the admin. You invite may or may not be granted based on the short information that you provide about why you want to become a member. You still get an opportunity to become a member by applying after 1 week of getting declined. The other pet parents or bloggers can read the first blog for free but need to sign up once that is done for them to become eligible to read blogs as a member. DogSwag may introduce payment features in the near or long-term future to make it more interesting and relevant for members to become a part of it.  
Your Obligations
DogSwag provides a unique platform for pet parents and pet bloggers where they can write and get paid by the minute every time a pet parent reads their blog. It provides them unique features to make their blogs interesting through images, links, videos, and other essential resources that helps make their blogs interesting to read and get appreciated. If there are any issues related to the blog or website than you would need to write into to founders@dogswag.club 
DogSwag allows pet parents to access the website and read the content for free. However it allows only one blog to be read for free and post that they need to sign up to Dogswag.club to read all the other blogs for free. The free model can be changed at any particular point in time of the service.   
You understand that the Website does not provide undeniable or errorless services. We hold no responsibility if the device or operating system used by you is not compatible with the Website and we shall not be held liable for any damage caused to you resulting from the usage of Website.
You also hereby agree and acknowledge that this Website is strictly for your personal use and shall not be used for any other purposes whatsoever including but not limited to the following acts: 
Copying, reproducing, distributing, selling, leasing, licensing, publicly displaying, transmitting, or broadcasting or making any derivative works of the Website through any medium unless otherwise expressly consented.
Intentionally corrupt, damage or inappropriately delete, alter or destroy any data on the Website.
Undertaking any business activity which is in competition with our business or modifying the service provided through us or its appearance using any technology or offer anything additional in any manner whatsoever without obtaining our prior consent.
Using the Website for any illegal or fraudulent or any such purpose which may result in violation of any law applicable in India or regulations made thereto.
Harassing or stalking any other users or otherwise interfering with any other person’s use of the Website. 
Providing any information or update anything on the Website that may infringe any intellectual property rights of any third party or make available on the Website any third-party content for which you do not have necessary consent to use such content. 
Abuse or misuse the Website, including gaining or attempting to gain unauthorized access to the Website or circumvent the security of the Website in any manner.
Allow the introduction of any program or data that has embedded in them any virus, worms or other harmful components such that it harms, disrupts or impedes the operation of the Website or alters or destroys any data in it.
Post any advertisements, promotional materials or business solicitations on the website or otherwise in the course of availing our services.
Share, post or otherwise make available any content that is false, misleading, inaccurate information or misrepresents or impersonates any other person or entity or post any content that is derogatory, misleading, hateful, racial, objectionable, vulgar, offensive, illegal or discriminatory.
You agree to use the Website, the services and the content provided therein in a lawful manner and in compliance with these Terms and Conditions. You understand and acknowledge that any breach or any violation of this clause will cause irreparable harm to us and we reserve the right to injunctive relief against any such violation. In case of breach of security or any other unauthorized use of your account, you shall immediately notify us of the same.
Intellectual Property
You agree and understand that all the intellectual property including but not limited to trademarks, logos and business identifiers, copyright, patents, trade secrets and designs as well all intellectual property rights in the form of including but not limited to images, layouts, text, processes, technology, software features and specifications, source code and know-how which form a part of the App and the Website are the sole property of the Company or its respective owners or licensors and you shall have no right to claim any rights over the same or in any manner misuse the same.  Use of the website and the Website does not confer any license or assignment to use any of the intellectual property belonging to the Company, its affiliates and suppliers or the respective owners. You understand and undertake that you shall not copy, download, reproduce, distribute, perform, republish display, post, transmit, create derivative works of above-mentioned intellectual property and use the same only for your and your child’s personal and non-commercial use.
In the event you feel that your IP is infringed you can write to us founders@dogswag.club and we may, after making necessary enquiries, take appropriate action in this regard including removing any infringed article or material from the Website and you agree to keep us indemnified against all claims and liabilities arising therefrom.
The Content
By submitting any information, material or content created by you on or through the services on the App/Website (“Content”), you grant us a royalty-free, non-exclusive, worldwide license (including the right to sublicense) to use, copy, download, reproduce, process, republish, display, post, transmit, create derivative works or otherwise adapt and modify as well as distribute the Content in any and all modes, media, platforms (existing or hereafter developed) and to associate the Content with you. If you choose to make your Content “public”, we do not take any liability for the manner in which any other user uses the Content. 
With respect to the Content that has been made public you provide to the Company, our affiliates or business partners, a license to create derivative works from, promote, exhibit, broadcast, syndicate, publicly perform, and publicly display such Content in any form and in any and all media or distribution methods or on third party provider platforms. The same shall be subject to the terms and conditions of such third-party provider platforms and the Company shall not be liable for the same.    
You agree to take complete responsibility for the Content posted and shared by you. You acknowledge that such Content shall be subject to checks by us and we reserve the right to take down, in our sole discretion and without notice any content or material that is illegal, defamatory, libellous, obscene, offensive, abusive, objectionable or anything that is likely to cause injury or hurt to any person or entity or violate any intellectual property of any person or entity or contains a virus or other harmful components likely to impede the operation of the App/Website or if you ohave been using the services to in any manner contrary to the provisions to these Terms and Conditions. 
Our Rights
You hereby acknowledge and agree that through the use of the Website you grant the Company the following rights:
All content, blogs, images, and other material uploaded onto DogSwag and featured on the website are 100% owned by DogSwag India Limited 
DogSwag India reserves the right to remove any product or service at any point in time from the website without taking any prior consent or providing any notification 
DogSwag India Limited products and services are for the purpose of consumption, learning, entertainment, informative, knowledge sharing, purchase, selling, advertising, and customer acquiring.
DogSwag India Limited is in no way responsible directly or indirectly to anything that happens to your dog or pet because of any of our blogs, product or services

Our Warranties and Disclaimers
Access to the Website as well as the services provided herein are on an “as-is” basis without making any representations and warranties, expressed or implied. These shall include but are not limited to the implied warranties of merchantability, fitness for a particular purpose, non- infringement, accuracy or likely results, uninterrupted service, loss or corruption of data. We do not warrant that the App/Website or the network system linked to it is free from any operational errors, virus, worm or any other harmful components though We shall take reasonable measures to remedy or avoid any such events. We shall not be held liable for any damages arising out of-
Any breach or impairment of any privacy, security or confidentiality of your information or any other information on the Website brought as a result of your acts, omissions or negligence;
Any incorrect or inaccurate information provided by you including personal information such as your email address;
Any unauthorized access or use of the Website or loss of any data, corruption, destruction, or misdirection of any transmissions or any liability from loss of service resulting from communication failures by telecommunication service providers or any other equipment failures;
Any defamatory, offensive, illegal or unlawful conduct committed by you.
Indemnification
You shall indemnify and hold us and our employees, officers, directors, agents and affiliates harmless from and against all third party claims, suits, liabilities, appeals, causes of action, casualty, expenses, damages, costs, fees, expenses including reasonable attorney fees emerging or arising from or relating to your use of our App/Website, any activity related to your account by you. 
Limitation of Liability
You hereby acknowledge and agree that we or our employees, agents, or affiliates shall not be liable for any losses or damages, whether direct or indirect, as a result of any unauthorized use or inability to use the Website, reliance on any content/product, any third-party platform or services, or any breach of the Terms and Conditions. This applies to all damages of any kind, including but not limited to any direct, indirect, special, incidental or consequential damages (including but not limited to loss of business or goodwill, revenue, profits, personal injury or property damage or other economic advantage) whether based on breach of contract, breach of warranty, tort (including negligence) or otherwise. Notwithstanding the foregoing, our sole and entire maximum liability for any reason, and your sole and exclusive remedy for any cause or claim whatsoever shall be limited to the amounts paid by you to us for the services availed by you.
Termination
We reserve the right to suspend and/or terminate your access to the Website, with or without notice, in the event you breach these Terms and Conditions stipulated herein. Where it is observed that there is any suspected illegal, fraudulent, indecent, abusive or objectionable activity on your or your child’s accord, it may amount to grounds for terminating your access to the App/Website and we may take any other appropriate action as we deem fit. Upon suspension or termination, we reserve the right to remove or delete your information including but not limited to login and account information and your right to the services on the App/Website shall immediately cease without notice.   
Miscellaneous
Assignment: Both the Parties shall not assign, sublicense or transfer any of its rights or obligations under these Terms and Conditions without the other Party’s prior written consent. The Parties shall indemnify and hold harmless the other against all liability, costs, and expenses, including but not limited to a reasonable attorneys’ fee, arising out of or in connection with claims relating to an attempted assignment, sublicense, or transfer of the other’s rights and obligations.
Governing Law and Jurisdiction: These Terms and Conditions shall be governed by and construed in accordance with the laws of the State of Karnataka and the Parties hereto irrevocably submit to the sole and exclusive jurisdiction of the courts at Bengaluru in respect of any dispute or matter arising out of or connected with these Terms and Conditions.
Waivers: The waiver by either party of a breach or other violation of any provision of this Terms and Conditions shall not operate as, or construed to be, a waiver of any subsequent breach of the same or other provision of this Terms and Conditions.
Force Majeure: We will not be liable for any failure to perform any obligations due to any cause beyond our reasonable control including, but without being limited to unavailability of communication systems, earthquake, terrorism, political riot or disturbance, governmental or judicial orders, invasion, war, threat or preparation for war, storm, flood, epidemic, pandemic or natural physical disaster.
Support: If you have any questions or queries relating to these Terms and Conditions, or wish to report any violation of these Terms and Conditions, and in case of any technical discrepancy you may contact us at founders@dogswag.club



Fees, Refund and Cancellation Policy
We will in the future charge membership fee, provide valued-added chargeable services for pet parents and pet bloggers.

Our Privacy Policy
In addition to the above-mentioned Terms and Conditions, by using the App or Website, you also acknowledge that you have read, understood and agree to be bound by our privacy policy (“Privacy Policy”) provided below:
The Company understands and acknowledges how important privacy is to you This Privacy Policy listed below provides a description of our online data collection and usage policies and practices. By registering or by using  the Website, you explicitly accept, without limitation or qualification, the Company’s policy regarding the collection, processing, use, sharing, disclosing and handling of the personal information provided by you in the manner described in this Privacy Policy and as amended by us. You also acknowledge that you have read, understood, and agree to be bound to all terms and conditions of this Privacy Policy. 
Processing, your information in any way, including, but not limited to, collecting, storing, deleting, using, combining, sharing, transferring and disclosing information, all of which activities will take place in India. This Privacy Policy is a legally binding electronic agreement formed under the Information Technology Act, 2000 and the Rules made thereunder and the provisions pertaining to electronic documents / records in various statutes in India as enacted and amended from time to time. 
Overview
Please take a moment to read this Privacy Policy so that you may understand how the App/website collects and uses your personal information and gives you an overview of our general rules on management of privacy. 
Kindly note that we may modify this Privacy Policy from time to time to bring about certain changes. As such, it is your responsibility to review this Privacy Policy regularly and to see when it was last updated. If we make any changes to this Privacy Policy, we may notify you on the App or via email. 
Your continued use of the App/website is deemed to be an acceptance of this Privacy Policy and any changes thereto. 
Information that we may collect
Whenever you use our website, we collect information from you based on your activities on the website. In some areas of our website, we request you to provide or submit Personally Identifiable Information about you and your dog. Here, Personally Identifiable Information includes: 



Personal and Contact Data: the only personally identifiable information that we may collect could be your email address, mobile number, city, no of dogs, breed, about you, location, and any other contact details, obtained as and when necessary. However, please note that as a fundamental rule the Company does not knowingly collect data, other than the information mentioned herein, from or about you without your permission. 

Financial Data: In order to make the fee payment you shall have to share your financial information such as your credit card/debit card number, bank information, expiration date, and verification code. 
Further, we may also collect Non-Personally Identifiable Information which includes but is not limited to the type and version of the device you use to access our App or our Website, your operating system, web browser information such as what type and version of the browser you are using, your Internet Protocol address (commonly known as IP address), your computer and mobile network and connection information, application usage, connectivity data, errors or event failures or general and/or aggregated location data. We may also collect technical data to address and fix technical problems and improve our services. 

Use of the information collected:
The website collects information from you in order to provide you an efficient, safe and secure user experience and also for one or more of the following purposes:
Quality improvement: To improve the quality and design of the website and to create new features, functionalities and services on the website by evaluating the performance of the services and measuring the effectiveness of the services, its contents or features;
Account activation: To contact you on your email address for updates, new toys releases, blogs, and promotional activities
Important updates and information: To send you important information regarding the website, our Terms of Use and any other important updates;
Technical problems: To help you address problems with the website or the Website, including addressing any technical or user based problems;
Understanding usage trends: To administer the application, analyse trends, gather demographic information, create internal quality standards, generate data analysis reports and usage trends and patterns;
For any other purposes disclosed to you at the time we collect your information or pursuant to your consent.
We will not track Non-Personally Identifiable Information such as specific IP address to identify an individual user, however, we reserve the right to use such information to identify a user to comply with legal requirements or in the event of any safety or security issues.
Further, we may also use the Personally Identifiable Information to solve any disputes, perform administrative actions, contact you, enforce our agreements with you, including our Terms and Conditions and this Privacy Policy, comply with applicable law, and cooperate with law enforcement authorities.
All the data or information posted or shared by you belongs to you and you will decide the sharing and disclosure of such information. We do not share any Personally Identifiable Information about you, without your consent to any third party except to perform our obligations in accordance with this Privacy Policy. 
Data-tracking and cookies
The website and/or our authorized trusted third parties, may automatically collect your non-personally identifiable information when you visit or use the website through the use of electronic tools like cookies and web-beacons or pixel tags. We use cookies and other identification technologies to enable certain functionalities and in order to monitor our services, diagnose issues as well as understand your preferences which will help improve our services. You reserve the right to accept or decline the cookies.
Third Parties
We may also share this information with our authorized trusted third parties, third party advertisers and collaborators as well as corporate affiliates who are subject to this policy to assist us in our business support functions and the same shall be done under strict confidentiality obligations. Such sharing shall be also done in accordance with applicable laws, Terms and Conditions, Privacy Policy or otherwise under mutual consent.
Interest-Based Advertising
The Company commits to not display any targeted advertising on the App or on the Website. However, the Website may allow third party advertisers to create certain fun sections on the Website which may include but would not be limited. The Website provides tools for such third-party advertisers to communicate with you directly and any communication from your end is completely your responsibility and accountability.
Further, there may be third-party service providers who serve interest-based advertising wherein you may be able to view targeted advertisements on other websites, apps or services or social networking platform based on information collected by such third-party service providers independently about your visits to our and other websites in order to provide advertisements about goods and services matching your interests. Please note that we do not have access to or control of the cookies that may be placed by the third-party service providers on our  Website. 
The Website may also maintain links of our social media handles for your convenience and if you choose to visit other websites, we shall not be responsible for the privacy policies or content of those other websites, and it is your responsibility to review the privacy policies and terms of use of those websites to confirm that you understand and agree with their practices and policies. 
Our data security policies
We insist upon maintaining the generally accepted industry standards to help protect information from loss, theft, misuse and unauthorized access, disclosure, alteration and destruction both at the time of transmission and once we receive it. In order to achieve this, we undertake certain security measures to safeguard your information from illegal and unauthorized access. We maintain commercially reasonable safeguards such as access controls, passwords, data security measures, anti-virus systems for security and protection of the information. You understand that no network system or Internet or any other public network can be guaranteed to be 100% secure. However, all the security measures undertaken by us are not absolutely safe and error-free. Though we strive to protect your and your child’s personal data, we cannot guarantee its absolute security and cannot disclaim the risk that our systems may be thwarted by a third party. Any information that you transmit to us would therefore be at your own risk.
Our data retention policies 
We may retain all information provided by you through your use of the Platform for as long as you access the Website and services. Once your account is terminated, we reserve the right to either delete your records from our website and systems immediately or we may retain your records for a specific term for the purpose of complying with legal obligations. Post such term, we shall delete the same from our website and systems.
Our legal obligations 
We reserve the right to disclose the information provided by you as required by law and when we believe that disclosure is necessary to protect our rights and/or to comply with a court order or legal process served on us, or to enforce or apply this Privacy Policy, Terms and Conditions or other agreements or to protect the rights or safety of the App.
Customer support and Newsletters
As part of availing our services we will send you automated system communications as per your settings through an email or other notifications. Your contact information may be used for customer support services. We may also use your contact information to send you newsletters, promotional offers, ongoing offers and you can opt-out of receiving such communications from us at any time. 
In the event of Company Acquisition 
In the event we are merged or acquired by another company, the successor company may acquire your information that we maintain and which will still remain subject to this Privacy Policy or such revised policy as the case may be.
Contact Information 
If you wish to correct or update any information provided to us by you, register a complaint, delete any information, de-authorize the collection of your information in the future, or have any questions and concerns regarding this Privacy Policy, please contact us at founders@dogswag.club. 

Last updated on 10th March 2023





		  </div>
		)
}