const breeds = [
    {value : 'afghan hound', label: 'Afghan hound' },
    {value : 'airedale terrier', label: 'Airedale terrier' },
    {value : 'akita', label: 'Akita'},
    {value : 'alaskan Malamute', label : 'Alaskan Malamute'},
    {value : 'american Staffordshire terrier', label : 'American Staffordshire terrier'},
    {value : 'american water spaniel', label : 'American water spaniel'},
    {value : 'australian cattle dog', label : 'Australian cattle dog'},
    {value : 'australian shepherd', label : 'Australian shepherd'},
    {value : 'australian terrier', label : 'Australian terrier'},
    {value : 'aasenji', label : 'basenji'},
    {value : 'aasset hound', label : 'basset hound'},
    {value : 'beagle', label : 'beagle'},
    {value : 'bearded collie', label : 'bearded collie'},
    {value : 'bedlington terrier', label : 'Bedlington terrier'},
    {value : 'bernese mountain dog', label : 'Bernese mountain dog'},
    {value : 'bichon frise', label : 'bichon frise'},
    {value : 'black and tan coonhound', label : 'black and tan coonhound'},
    {value : 'bloodhound', label : 'bloodhound'},
    {value : 'border collie', label : 'border collie'},
    {value : 'border terrier', label : 'border terrier'},
    {value : 'borzoi', label : 'borzoi'},
    {value : 'boston terrier', label : 'Boston terrier'},
    {value : 'bouvier des Flandres', label : 'bouvier des Flandres'},
    {value : 'boxer', label : 'boxer'},
    {value : 'briard', label : 'briard'},
    {value : 'brittany', label : 'Brittany'},
    {value : 'brussels griffon', label : 'Brussels griffon'},
    {value : 'bull terrier', label : 'bull terrier'},
    {value : 'bulldog', label : 'bulldog'},
    {value : 'bullmastiff', label : 'bullmastiff'},
    {value : 'cairn terrier', label : 'cairn terrier'},
    {value : 'banaan dog', label : 'Canaan dog'},
    {value : 'bhesapeake Bay retriever', label : 'Chesapeake Bay retriever'},
    {value : 'bhihuahua', label : 'Chihuahua'},
    {value : 'bhinese crested', label : 'Chinese crested'},
    {value : 'bhinese shar-pei', label : 'Chinese shar-pei'},
    {value : 'chow chow', label : 'chow chow'},
    {value : 'blumber spaniel', label : 'Clumber spaniel'},
    {value : 'cocker spaniel', label : 'cocker spaniel'},
    {value : 'collie', label : 'collie'},
    {value : 'curly-coated retriever', label : 'curly-coated retriever'},
    {value : 'dachshund', label : 'dachshund'},
    {value : 'balmatian', label : 'Dalmatian'},
    {value : 'boberman pinscher', label : 'Doberman pinscher'},
    {value : 'bnglish cocker spaniel', label : 'English cocker spaniel'},
    {value : 'bnglish setter', label : 'English setter'},
    {value : 'bnglish springer spaniel', label : 'English springer spaniel'},
    {value : 'bnglish toy spaniel', label : 'English toy spaniel'},
    {value : 'bskimo dog', label : 'Eskimo dog'},
    {value : 'binnish spitz', label : 'Finnish spitz'},
    {value : 'flat-coated retriever', label : 'flat-coated retriever'},
    {value : 'fox terrier', label : 'fox terrier'},
    {value : 'foxhound', label : 'foxhound'},
    {value : 'French bulldog', label : 'French bulldog'},
    {value : 'berman shepherd', label : 'German shepherd'},
    {value : 'berman shorthaired pointer', label : 'German shorthaired pointer'},
    {value : 'berman wirehaired pointer', label : 'German wirehaired pointer'},
    {value : 'golden retriever', label : 'golden retriever'},
    {value : 'bordon setter', label : 'Gordon setter'},
    {value : 'breat Dane', label : 'Great Dane'},
    {value : 'greyhound', label : 'greyhound'},
    {value : 'irish setter', label : 'Irish setter'},
    {value : 'irish water spaniel', label : 'Irish water spaniel'},
    {value : 'irish wolfhound', label : 'Irish wolfhound'},
    {value : 'jack Russell ', label : 'Jack Russell '},
    {value : 'terrier', label : 'terrier'},
    {value : 'japanese spaniel', label : 'Japanese spaniel'},
    {value : 'keeshond', label : 'keeshond'},
    {value : 'kerry blue terrier', label : 'Kerry blue terrier'},
    {value : 'komondor', label : 'komondor'},
    {value : 'kuvasz', label : 'kuvasz'},
    {value : 'labrador retriever', label : 'Labrador retriever'},
    {value : 'lakeland terrier', label : 'Lakeland terrier'},
    {value : 'lhasa apso', label : 'Lhasa apso'},
    {value : 'maltese', label : 'Maltese'},
    {value : 'manchester terrier', label : 'Manchester terrier'},
    {value : 'mastiff', label : 'mastiff'},
    {value : 'mexican hairless', label : 'Mexican hairless'},
    {value : 'ewfoundland', label : 'Newfoundland'},
    {value : 'orwegian elkhound', label : 'Norwegian elkhound'},
    {value : 'orwich terrier', label : 'Norwich terrier'},
    {value : 'otterhound', label : 'otterhound'},
    {value : 'papillon', label : 'papillon'},
    {value : 'Pekingese', label : 'Pekingese'},
    {value : 'pointer', label : 'pointer'},
    {value : 'Pomeranian', label : 'Pomeranian'},
    {value : 'poodle', label : 'poodle'},
    {value : 'pug', label : 'pug'},
    {value : 'puli', label : 'puli'},
    {value : 'rhodesian ridgeback', label : 'Rhodesian ridgeback'},
    {value : 'rottweiler', label : 'Rottweiler'},
    {value : 'saint Bernard', label : 'Saint Bernard'},
    {value : 'saluki', label : 'saluki'},
    {value : 'samoyed', label : 'Samoyed'},
    {value : 'schipperke', label : 'schipperke'},
    {value : 'schnauzer', label : 'schnauzer'},
    {value : 'scottish deerhound', label : 'Scottish deerhound'},
    {value : 'scottish terrier', label : 'Scottish terrier'},
    {value : 'sealyham terrier', label : 'Sealyham terrier'},
    {value : 'shetland sheepdog', label : 'Shetland sheepdog'},
    
  ];

export default breeds